name: Construyendo app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code  
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install python-nmap paramiko termcolor requests

    - name: Run script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python3 Fussion/fussion_multitool.py
